name: 🛡️ CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

# Permisos necesarios para el workflow llamado
permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  ci:
    uses: ROKO108/.github/.github/workflows/universal-ci.yml@main
    with:
      validate_all: false
    secrets: inherit
